package com.preschool.demo.type;

import org.apache.commons.lang3.StringUtils;

public enum MessageType {
    ACCESS_DENIED("ACCESS_DENIED"),
    BAD_CREDENTIALS("BAD_CREDENTIALS"),
    OPERATION_NOT_SUPPORTED("OPERATION_NOT_SUPPORTED"),
    USERNAME_ALREADY_DEFINED("USERNAME_ALREADY_DEFINED"),
    NAME_ALREADY_DEFINED("NAME_ALREADY_DEFINED"),
    EMAIL_ALREADY_DEFINED("EMAIL_ALREADY_DEFINED"),
    DESCRIPTION_ALREADY_DEFINED("DESCRIPTION_ALREADY_DEFINED"),
    INVALID_EMAIL_PATTERN("INVALID_EMAIL_PATTERN"),
    MSISDN_ALREADY_DEFINED("MSISDN_ALREADY_DEFINED"),
    INVALID_USERNAME_PATTERN("INVALID_USERNAME_PATTERN"),
    INVALID_MSISDN_PATTERN("INVALID_MSISDN_PATTERN"),
    CODE_ALREADY_DEFINED("CODE_ALREADY_DEFINED"),
    BOTH_OF_AUTHORITY_AND_ROLE_CAN_NOT_BLANK("BOTH_OF_AUTHORITY_AND_ROLE_CAN_NOT_BLANK"),
    USERNAME_CAN_NOT_BLANK("USERNAME_CAN_NOT_BLANK"),
    USER_ID_CAN_NOT_BLANK("USER_ID_CAN_NOT_BLANK"),
    USER_TOKEN_CAN_NOT_BLANK("USER_TOKEN_CAN_NOT_BLANK"),
    ROOM_ID_CAN_NOT_BLANK("ROOM_ID_CAN_NOT_BLANK"),
    DEVICE_ID_CAN_NOT_BLANK("DEVICE_ID_CAN_NOT_BLANK"),
    DEVICE_NAME_CAN_NOT_BLANK("DEVICE_NAME_CAN_NOT_BLANK"),
    DEVICE_CODE_CAN_NOT_BLANK("DEVICE_CODE_CAN_NOT_BLANK"),
    ROLL_CALL_STATUS_CAN_NOT_BLANK("ROLL_CALL_STATUS_CAN_NOT_BLANK"),
    ROOM_DEVICE_ALREADY_DEFINED("ROOM_DEVICE_ALREADY_DEFINED"),
    NAME_CAN_NOT_BLANK("NAME_CAN_NOT_BLANK"),
    DEPARTMENT_CAN_NOT_BLANK("DEPARTMENT_CAN_NOT_BLANK"),
    ROOM_ALREADY_DEFINED("ROOM_ALREADY_DEFINED"),
    BODY_CAN_NOT_BLANK("BODY_CAN_NOT_BLANK"),
    FIRST_NAME_CAN_NOT_BLANK("FIRST_NAME_CAN_NOT_BLANK"),
    LAST_NAME_CAN_NOT_BLANK("LAST_NAME_CAN_NOT_BLANK"),
    TYPE_CAN_NOT_BLANK("TYPE_CAN_NOT_BLANK"),
    PASSWORD_CAN_NOT_BLANK("PASSWORD_CAN_NOT_BLANK"),
    CODE_CAN_NOT_BLANK("CODE_CAN_NOT_BLANK"),
    DESCRIPTION_CAN_NOT_BLANK("DESCRIPTION_CAN_NOT_BLANK"),
    ASSESSMENT_IS_ACTIVE_CAN_NOT_DELETE("ASSESSMENT_IS_ACTIVE_CAN_NOT_DELETE"),
    ASSESSMENT_IS_PUBLISHED_CAN_NOT_DELETE("ASSESSMENT_IS_PUBLISHED_CAN_NOT_DELETE"),
    LANGUAGE_CAN_NOT_BLANK("LANGUAGE_CAN_NOT_BLANK"),
    TENANT_COULD_NOT_FOUND("TENANT_COULD_NOT_FOUND"),
    LANGUAGE_COULD_NOT_FOUND("LANGUAGE_COULD_NOT_FOUND"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_NOT_FOUND_NEED_TO_REGISTRATION("USER_NOT_FOUND_NEED_TO_REGISTRATION"),
    USER_CODE_CAN_NOT_BLANK("USER_CODE_CAN_NOT_BLANK"),
    OLD_PASSWORD_CAN_NOT_BLANK("OLD_PASSWORD_CAN_NOT_BLANK"),
    NEW_PASSWORD_CAN_NOT_BLANK("NEW_PASSWORD_CAN_NOT_BLANK"),
    WRONG_PASSWORD_OR_USERNAME("WRONG_PASSWORD_OR_USERNAME"),
    NEW_PASSWORD_AND_CONFIRM_PASSWORD_ARE_NOT_SAME("NEW_PASSWORD_AND_CONFIRM_PASSWORD_ARE_NOT_SAME"),
    OLD_AND_NEW_PASSWORD_ARE_SAME("OLD_AND_NEW_PASSWORD_ARE_SAME"),
    CAN_NOT_REMOVE_TENANT_BECAUSE_USER_MUST_HAS_LEAST_ONE_TENANT("CAN_NOT_REMOVE_TENANT_BECAUSE_USER_MUST_HAS_LEAST_ONE_TENANT"),
    ROLE_IN_USED_CAN_NOT_DELETE("ROLE_IN_USED_CAN_NOT_DELETE"),
    MIN_VALUE_CAN_NOT_BLANK("MIN_VALUE_CAN_NOT_BLANK"),
    MAX_VALUE_CAN_NOT_BLANK("MAX_VALUE_CAN_NOT_BLANK"),
    START_DATE_CAN_NOT_AFTER_END_DATE("START_DATE_CAN_NOT_AFTER_END_DATE"),
    SLOT_COULD_NOT_FOUND("SLOT_COULD_NOT_FOUND"),
    SLOT_ID_CAN_NOT_BLANK("SLOT_ID_CAN_NOT_BLANK"),
    SLOT_IS_NOT_AVAILABLE("SLOT_IS_NOT_AVAILABLE"),
    SLOT_IS_NOT_ACTIVE("SLOT_IS_NOT_ACTIVE"),
    ACTION_TYPE_CAN_NOT_CHANGE("ACTION_TYPE_CAN_NOT_CHANGE"),
    BLOCK_ID_CAN_NOT_BLANK("BLOCK_ID_CAN_NOT_BLANK"),
    SLOT_CAN_NOT_BLOCK("SLOT_CAN_NOT_BLOCK"),
    ONLINE_DURATION_CAN_NOT_BLANK("ONLINE_DURATION_CAN_NOT_BLANK"),
    SLOT_ALREADY_ACTIVE("SLOT_ALREADY_ACTIVE"),
    COURSE_CODE_NOT_FOUND("COURSE_CODE_NOT_FOUND"),
    DEVICE_UNIQUE_ID_CAN_NOT_BLANK("DEVICE_UNIQUE_ID_CAN_NOT_BLANK"),
    DEVICE_ALREADY_DEFINED("DEVICE_ALREADY_DEFINED"),
    DEVICE_ALREADY_IN_USE_FOR_OTHER_USER("DEVICE_ALREADY_IN_USE_FOR_OTHER_USER"),
    SLOTS_CAN_NOT_BE_BLOCK("SLOTS_CAN_NOT_BE_BLOCK"),
    ROLLCALL_OUT_NOTIFICATION("ROLLCALL_OUT_NOTIFICATION"),
    SLOT_DEVICE_NOTIFICATION("SLOT_DEVICE_NOTIFICATION"),



    ;

    private String key;

    MessageType(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }

    @Override
    public String toString() {
        return this.getKey() + StringUtils.EMPTY;
    }
}
